version: "3"

services:
  grpcserver:
    image: jun06t/grpc-backend-prometheus
    environment:
      ENDPOINT: ":8080"
      PROMETHEUS_METRICS_ADDR: ":9100"

  grpcclient:
    image: jun06t/grpc-gateway-prometheus
    ports:
      - 8080:8080
    environment:
      ENDPOINT: "grpcserver:8080"
      API_ADDR: ":8080"
      PROMETHEUS_METRICS_ADDR: ":9100"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - grpcserver
      - grpcclient

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - grpcserver
      - grpcclient
