FROM golang:1.12-alpine

ARG REPO="github.com/jun06t/prometheus-sample/grpc-gateway"

RUN apk add --no-cache git ca-certificates \
  && mkdir -p /go/src/${REPO}
COPY . /go/src/${REPO}

WORKDIR /go/src/${REPO}

RUN GO111MODULE=on go build -o grpc-gateway ./gateway/* && \
  mv grpc-gateway /usr/local/bin/

EXPOSE 3000

CMD ["grpc-gateway"]
