FROM golang:1.12-alpine

RUN apk add --no-cache git ca-certificates \
  && mkdir -p src
COPY . ${HOME}/src

WORKDIR ${HOME}/src

RUN GO111MODULE=on go build -o grpc-backend ./server/* && \
  mv grpc-backend /usr/local/bin/

EXPOSE 8080
EXPOSE 9100

CMD ["grpc-backend"]
