global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'grpcserver'
    static_configs:
    - targets: ['grpcserver:9100']
  - job_name: 'grpcclient'
    static_configs:
    - targets: ['grpcclient:9100']
