apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: "jun06t/grpc-gateway-prometheus"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        - containerPort: 9100
        env:
        - name: API_ADDR
          value: ":3000"
        - name: ENDPOINT
          value: "backend-svc:10000"
        - name: PROMETHEUS_METRICS_ADDR
          value: ":9100"
