apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: ClusterIP
  ports:
  - name: app
    protocol: TCP
    port: 10000
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 10001
    targetPort: 9100
  selector:
    app: backend-service
