apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy
spec:
  type: NodePort
  ports:
  - name: proxy
    protocol: TCP
    port: 80
    targetPort: 9090
  selector:
    app: prometheus
