{
 "title": "gRPC",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "method", "query": "grpc_server_handled_total" }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Requests / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_method,grpc_service)(rate(grpc_client_handled_total{grpc_method=~\"$method\"}[1m]))",
     "legendFormat": "{{ grpc_service }} - {{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Backend Requests / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_method,grpc_service)(rate(grpc_server_handled_total{grpc_method=~\"$method\"}[1m]))",
     "legendFormat": "{{ grpc_service }} - {{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Client Requests / sec by Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_code)(rate(grpc_client_handled_total{grpc_method=~\"$method\"}[1m]))",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Backend Requests / sec by Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_code)(rate(grpc_server_handled_total{grpc_method=~\"$method\"}[1m]))",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Client Internal or Unknown error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_method)(rate(grpc_client_handled_total{grpc_code=~\"(Unknown|Internal)\",grpc_method=~\"$method\"}[1m]))\n/\nsum by(grpc_method)(rate(grpc_client_handled_total{grpc_method=~\"$method\"}[1m]))",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Backend Internal or Unknown error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_method)(rate(grpc_server_handled_total{grpc_code=~\"(Unknown|Internal)\",grpc_method=~\"$method\"}[1m]))\n/\nsum by(grpc_method)(rate(grpc_server_handled_total{grpc_method=~\"$method\"}[1m]))",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Client Average duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_client_handling_seconds_sum[1m])\n/\nrate(grpc_client_handling_seconds_count[1m])",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Backend Average duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handling_seconds_sum[1m])\n/\nrate(grpc_server_handling_seconds_count[1m])",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  }
 ]
}