{
 "title": "HTTP Dashboard",
 "time": { "from": "2019-07-18T07:45:50.358Z", "to": "2019-07-18T07:52:26.049Z" },
 "panels": [
  {
   "title": "Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(handler, method)(rate(http_requests_total[1m]))",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  },
  {
   "title": "Requests/sec by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(code)(rate(http_requests_total[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "4xx error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(handler, method)(rate(http_requests_total{code=~\"4..\"}[1m])) / sum by(handler, method)(rate(http_requests_total[1m]))",
     "legendFormat": "{{ handler }} - {{ method }}"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(handler, method)(rate(http_requests_total{code=~\"5..\"}[1m]))/ sum by(handler, method)(rate(http_requests_total[1m]))",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[1m])/rate(request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  },
  {
   "title": "Request Duration 50%ile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(request_duration_seconds_bucket[1m]))",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  },
  {
   "title": "Request Duration 90%ile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_duration_seconds_bucket[1m]))",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  }
 ]
}